server:
  port: 8080
spring:
  application:
    name: spring-ai
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-ai
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${GEMINI_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemini-3.6-flash
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always